### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by Sh3ngYu** [lolouk44/hassio-addons#45]
Hello there, after lot of hour searching what is wrong, I come there for some help please.
Nothing happen when I go on the scale.

My CFG :
https://postimg.cc/gallery/7fXq8MN

**Comment by lolouk44** [comment]
I think your issues may be linked to the way you set your config.
Try to enclose your Scale MAC address in single quotes
Also try a tool like MQTT Explorer to ensure your MQTT Broker does receive data...

**Comment by Sh3ngYu** [comment]
Thank you for you fast anwser, sadly when I write the single quotes for enclose my scale Mac address they disapear when I click on save
MISCALE_MAC: '0C:95:41:AC:AF:B8'

**Comment by lolouk44** [comment]
ok. 
I'm gonna need more information. Please fill the template this time:

**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour, including error message if any.

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Scale (please complete the following information):**
 - Name
 - Model #

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 - Bluetooth device used [e.g. Built-in, USB Dongle]

**Additional context**
Add any other context about the problem here.


Do you have the Xiaomi app open as well? You need to make sure it's not as you can only have 1 connection to the scale via bluetooth.
What happens when you step on the scale? Do you get anything in the logs?

**Comment by Sh3ngYu** [comment]
Holy god, Fly mod resolve the problem. Thx you a lot for this add-on and your help <3
